# version: '3.9'
# services:
#   db:
#     image: mongo:latest
#     container_name: mongo-container
#     restart: always
#     ports:
#       - 27017:27017
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=travis
#       - MONGO_INITDB_ROOT_PASSWORD=secret
#   db-container:
#     image: mongo-express
#     container_name: mongo-db-container
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       - ME_CONFIG_MONGODB_ADMINUSERNAME=travis
#       - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
#       - ME_CONFIG_MONGODB_URL=mongodb://travis:secret@db:27017/
#     depends_on:
#       - db

# version: '3.9'
# services:
#   db:
#     image: mongo:latest
#     container_name: mongo-container
#     restart: always
#     ports:
#       - 27017:27017
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=travis
#       - MONGO_INITDB_ROOT_PASSWORD=secret

#   mongo-express:
#     image: mongo-express:latest
#     container_name: mongo-express-container
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
#       - ME_CONFIG_AUTH_USERNAME=travis
#       - ME_CONFIG_AUTH_PASSWORD=secret
#       - ME_CONFIG_MONGODB_URL=mongodb://travis:secret@db:27017/
#     depends_on:
#       - db

version: "3.9"

services:
  mongodb:
    container_name: ${DB_CONTAINER_NAME}
    image: "mongo:latest"
    environment: 
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - "27017:27017"